version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_USER: topazadmin
      MYSQL_PASSWORD: topazisawesome
      MYSQL_ROOT_PASSWORD: topazisawesome
      MYSQL_DATABASE: tpzdb

    volumes: 
      - ./sql:/docker-entrypoint-initdb.d

    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    depends_on: 
      - "db"
    ports:
      - 8080:8080

  code:
    build: .
    depends_on: 
      - "db"
    ports:
      - "54230:54230/tcp"
      - "54231:54231/tcp"
      - "54001:54001/tcp"
      - "54002:54002/tcp"
      - "54230:54230/udp"